#Create Product
POST http://localhost:9000/products
Content-Type: application/json

    {
        "name": "iwatch",
        "description": " apple watch",
        "price": 1000,
        "stock": 12
    }

### Get products
GET http://localhost:9000/products
Content-Type: application/json

### Update Stock
PATCH http://localhost:9000/products/3
Content-Type: application/json

    {
        "stock": 50
    }