#Create Product
POST http://localhost:9000/products

Content-Type: application/json
{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "stock": 10
}
### Get products
GET http://localhost:9000/products
Content-Type: application/json

### Update Stock
PATCH http://localhost:9000/products/2
Content-Type: application/json

    {
        "stock": 50
    }